#ifndef __print_task_H    // header files should include guards
#define __print_task_H

#include "cmsis_os.h"

typedef struct {
  int id;
  TaskHandle_t handle;  // generated by FreeRTOS, saved for later use (task synchronization, etc.)
  char task_name[16];
} PRINT_PARAMS_t;

void print_task(void *parameters);
void print_task_init(int id, char *task_name);


#endif
