#ifndef __teller_task_H    // header files should include guards
#define __teller_task_H

#include "cmsis_os.h"

typedef struct {
  int id;
  TaskHandle_t handle;  // generated by FreeRTOS, saved for later use (task synchronization, etc.)
  char task_name[16];
} TELLER_PARAMS_t;

void teller_task(void *parameters);
void teller_task_init(int id, char *task_name);


#endif
